# --- FILE PATHS ---
VOCAB_PATH = "models/vocab.json"
RUNS_DIR = "training_logs"

# --- TRAINING CONFIG ---
INPUT_DIM = 134
ENC_EMB_DIM = 256
DEC_EMB_DIM = 256
HID_DIM = 1024
N_LAYERS = 3
ENC_DROPOUT = 0.4
DEC_DROPOUT = 0.15
LEARNING_RATE = 0.0005
WEIGHT_DECAY = 1e-5
BATCH_SIZE = 64
N_EPOCHS = 50
CLIP = 1.0
VAL_SUBSET_SIZE = 200
DEFAULT_ENCODER_ARCH = "bilstm"
